apiVersion: v1
kind: ConfigMap
metadata:
   name: nginx-configmap22
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="ru">
    <head>
      <meta charset="UTF-8">
      <title>Task26</title>
    </head>
    <body>
    <h1>Tasks26</h1>

    <a href="/page1" target="_blank">1. Страница</a> <br>
    <a href="music/ms1.mp3" download>2. Скачать Музыку</a> <br>
    <a href="/image1/" target="_blank">3. image1</a><br>
    <a href="/image2/" target="_blank">4. image2</a><br>
    <a href="/4xx" target="_blank">5. 4xx</a><br>
    <a href="/5xx" target="_blank">6. 5xx</a><br>
    <a href="/proxy" target="_blank">7. proxy</a><br>
    <br>
      <p>Jenkins K8S.v.4</p>
    </body>
    </html>